// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLNEaz9Q3wHpdwY4Uc09ZD6R_2UUkiY14',
    appId: '1:138963298951:web:909641bfcd0ed058106622',
    messagingSenderId: '138963298951',
    projectId: 'crud-fgd7',
    authDomain: 'crud-fgd7.firebaseapp.com',
    storageBucket: 'crud-fgd7.appspot.com',
    measurementId: 'G-T5K81XH423',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwPucy5t6ALXA3Zzzifs-QCkNwmxd8xME',
    appId: '1:138963298951:android:b0953013b19c6b6f106622',
    messagingSenderId: '138963298951',
    projectId: 'crud-fgd7',
    storageBucket: 'crud-fgd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP7wtwe0AQx3KcoWMNfYnsO1pjX-ROhS8',
    appId: '1:138963298951:ios:137646ccecbcc6c6106622',
    messagingSenderId: '138963298951',
    projectId: 'crud-fgd7',
    storageBucket: 'crud-fgd7.appspot.com',
    iosBundleId: 'com.example.crudFirebase2',
  );
}
